[main]
include=/usr/share/foot/themes/nord

# font=JetBrainsMono Nerd Font Mono:size=12
# font=GeistMono Nerd Font:size=16
font=CaskaydiaCove Nerd Font Mono:size=13
# font=FiraCode Nerd Font:size=14
# font=MesloLGM Nerd Font:size=16
# font=Hack:size=12
# font=Terminess Nerd Font:size=13
pad=20x20

[cursor]
style=beam
blink=yes

[colors]
# alpha=0.95

# catppuccin-mocha
# background=11111b

# gruvbox
# background=1d2021

# general
# background=16181A

# nordic
# background=242933
# background=222630
# background=111317
background=101017
