[main]
include=/usr/share/foot/themes/cyberdream

font=JetBrainsMono Nerd Font Mono:size=12
# font=GeistMono Nerd Font:size=16
# font=CaskaydiaCove Nerd Font Mono:size=13
# font=FiraCode Nerd Font:size=14
# font=MesloLGM Nerd Font:size=16
# font=Hack:size=12
pad=20x20

[tweak]

[colors]
alpha=0.98

# catppuccin-mocha
# background=11111b

# gruvbox
# background=1d2021
# background=1d2021
