[main]
include= /usr/share/foot/themes/cyberdream
# include=/usr/share/foot/themes/catppuccin-mocha

# font=JetBrainsMono Nerd Font:size=12
# font=GeistMono Nerd Font:size=16
# font=CaskaydiaCove Nerd Font Mono:size=14
# font=FiraCode Nerd Font:size=16
# font=MesloLGM Nerd Font:size=16
# font=Hack:size=12
# font=Terminess Nerd Font:size=14
font=SauceCodePro Nerd Font:size=14
pad=12x12

# [cursor]
# style=beam
# blink=yes

[colors-dark]
alpha=0.90

# catppuccin-mocha
# background=1E1E2E
# background=11111b

# gruvbox
# background=1d2021

# general
# background=16181A

# nordic
# background=242933
# background=222630
# background=111317
# background=101017

# Black
background=000000
